# Generated by Django 2.2.7 on 2019-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='chosen_plan_id',
            field=models.IntegerField(null=True),
        ),
    ]
