# Generated by Django 2.2.7 on 2019-11-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0002_auto_20191116_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhdata.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhdata.Review'),
        ),
    ]
