# Generated by Django 2.2.7 on 2019-11-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0003_auto_20191116_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='final_chosen_plan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
