# Generated by Django 2.2.7 on 2019-11-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0002_auto_20191116_0815'),
        ('dhdata', '0004_auto_20191116_0810'),
    ]

    operations = [
    ]
