# Generated by Django 2.2.7 on 2019-11-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0004_auto_20191116_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='patient_id',
            field=models.CharField(max_length=200),
        ),
    ]
