# Generated by Django 2.2.7 on 2019-11-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0005_auto_20191116_0824'),
        ('dhdata', '0005_merge_20191116_0821'),
    ]

    operations = [
    ]
