# Generated by Django 2.2.7 on 2019-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0009_auto_20191116_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='chosen_plan_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
