# Generated by Django 2.2.7 on 2019-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhdata', '0010_auto_20191116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='final_chosen_plan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
